---
output:
  html_document:
    theme: yeti
    toc: yes
    toc_float: yes
---

# Recent Publications

---

# Hepatitis B vaccination coverage across India: exploring the spatial heterogeneity and contextual determinants

**Background**

Although hepatitis B vaccinations have been integrated in the Universal Immunization Program (UIP) in India over a decade, only half of the children are immunized against hepatitis B. The national average in hepatitis B vaccination conceals large variations across states, districts and socio-economic groups. In this context, the aim of this paper is to examine the spatial heterogeneity and contextual determinants of hepatitis B vaccination across the districts of India.

**Methods**

Using data of 199,899 children aged 12–59 months from the National Family Health Survey-4 (NFHS-4), 2015–16 we have examined the district level spatial distribution and clustering of hepatitis B vaccination with the help of Moran’s I and Local Indicator of Spatial Autocorrelation (LISA) measures. We investigated the low coverage of HBV vaccination using spatial autoregressive models (SAR) at the meso scale. And we applied multivariate binary logistic regression analysis to understand the micro-level predictors of hepatitis B vaccination.

**Results**

In 2015–16, 45% of the children aged 12–59 months were not vaccinated against hepatitis B in India. The coverage of hepatitis B vaccine across the districts of India showed a highly significant spatial dependence (Moran’s I= 0.580). Bivariate Moran’s I confirmed the spatial clustering of hepatitis B vaccination with mother’s education, full antenatal care (ANC) utilization, post natal care (PNC) utilization, institutional births and registration of births at the district level. Districts with a very low coverage of HBV vaccine are clustered in the western, north-eastern regions and in some parts of central India. At the unit (child) level, children’s hepatitis B immunization status is mostly determined by the socio-economic and demographic characteristics like their mother’s educational status, caste, religion, household’s wealth condition, birth order, year of birth and the region they belong to.

**Conclusions**

District level variation in hepatitis B vaccination is spatially heterogeneous and clustered in India with a strong neighbourhood effect. Uptake of hepatitis B vaccine among Indian children is predominantly dependent upon their socio-economic and demographic characteristics.

*You can access the full text version of this piece of work at* [here](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-019-7534-2).

---

# Exploring the spatial heterogeneity in different doses of vaccination coverage in India

**Background**

Despite the universalization of immunization against the six vaccine-preventable diseases (VPDs), the coverage of full immunization among the children under age five has remained a challenge globally. The 2015–16 National Family Health Survey (NFHS) indicated large disparity in the coverage of different vaccination doses (BCG, Polio, DPT and Measles) including full immunization across the districts of India. The spatial distribution of poor performing districts in terms of vaccination and the district level spatial, contextual determinants contributing to the low coverage have been poorly studied. Using the recent household survey (NFHS, 2015–16), this study examined the spatial heterogeneity and the factors associated with low vaccination coverage among the children aged 12–23 months across India.

**Data and methods**

This study used the data from fourth round of National Family Health Survey conducted in 2015–16. District-level prevalence of each of the vaccination doses including full immunization, were analysed. Moran’s I, Univariate and Bivariate LISA, Ordinary least square (OLS) and spatial models were employed to achieve the overall aim of the study.

**Results**

At the national level, the prevalence of full immunization was 62 percent. Specific vaccination coverage for BCG, three doses of polio, three doses of DPT and measles were 92, 73, 78 and 81 percent, respectively. The value of the bivariate Moran’s I statistics confirmed the spatial dependence between specific vaccination and the set of independent variables. District-level prevalence of the specific vaccine and full immunization showed significant spatial clustering across India. The adjusted coefficients from the spatial error model confirmed that district-level proportion of utilization of post-natal care, institutional births, neonatal tetanus protection of the last birth, women’s education and coverage of health insurance showed statistically significant association with every doses of vaccination coverage.

**Conclusion**

The full and specific immunization coverage was considerably low in the geographical hotspots as compared to the national coverage. Maternal and child health care services utilization, financial assistance to the mothers through JSY scheme and mother’s education were found to determine full immunization as well as the specific vaccination coverage. Appropriate intervention should be designed to reduce the geographical disparity in the coverage of specific and full immunization across India and thus safeguard child health protecting the children from the vaccine preventable diseases across the geography.

*You can access the full text version of this piece of work at* [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0207209).

---

# A geospatial analysis of noncommunicable disease (NCD) burden in Indian agro-climatic and political regions

**Aim**

To examine the burden of noncommunicable diseases (NCDs) in the Indian agro-climatic and political regions.

**Subjects and methods**

Data from two rounds of National Sample Survey (NSS) 68th (2011–12) and 71st (2014) was used to estimate the subnational spatial heterogeneity of NCD burden across 87 agro-climatic and political regions in India. Quantile maps, local Moran’s I, LISA cluster and significance maps were generated.

**Results**

Results show a high spatial heterogeneity in disease burden across the agro-climatic regions. Moran’s I scatterplot depict a significantly high level of regional dependence (Moran’s I=0.558) of NCDs with larger concentration of disease in southern states like Kerala (northern and southern), Tamil Nadu (inland, coastal, and northern-coastal), Karnataka (inland, coastal and Ghats) and Pondicherry. The proportion of the elderly population, those belonging to urban areas, widowed/divorced/separated population, high  per capita alcohol and tobacco consumption were more likely to affect the prevalence of NCDs.

**Conclusion**

Findings call for an immediate programmatic attention at the subnational level due to significantly high regional dependence of NCDs. Policies and programme should focus on strengthening the implementation of existing  policies with a special focus on geriatric population to combat the disease burden.

*You can access the full text version of this piece of work at* [here](https://link.springer.com/article/10.1007/s10389-017-0876-2).

---
